# Site settings
title: Ít học - Nhặt nhạnh
description: A blog about tech tips
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ithoc.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: ithoc
user_description: ithoc
email: github.com/ithoc/ithoc.github.io/issues
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
